In [1]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([[4, 5, 6]])

result = np.array([a, b[0]])

print(result)

[[1 2 3]
 [4 5 6]]


In [2]:
import numpy as np
arr = np.array([[1, 2], [3, 4]])
print(arr.flatten())

[1 2 3 4]


In [3]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr[::-1])

[5 4 3 2 1]


In [5]:
import numpy as np
arr=np.array([10,5,59,35,60])
print(np.max(arr))
print(np.min(arr))

60
5


In [7]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr.shape)
print("Rows =", arr.shape[0])
print("Columns =", arr.shape[1])

(2, 3)
Rows = 2
Columns = 3


In [10]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr[0][1]) 
print(arr[0][2]) 

print(arr[1])      
print(arr[0])

2
3
[4 5 6]
[1 2 3]


In [11]:
import numpy as np

arr = np.array([[1, 2], [3, 4]])
s = 0
for row in arr:
    for x in row:
        s += x

print(s)

10


In [12]:
import numpy as np

a = np.array([10, 20, 30])
b = np.array([1, 2, 3])
print(a + b)
print(a - b)
print(a * b)
print(a / b)

[11 22 33]
[ 9 18 27]
[10 40 90]
[10. 10. 10.]


In [13]:
import numpy as np

arr = np.array([[[1, 2], [3, 4]],
                [[5, 6], [7, 8]]])

for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


In [14]:
import numpy as np

arr = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])
for i in arr:
    for j in i:
        for k in j:
            print(k)

1
2
3
4
5
6
7
8


In [15]:
import numpy as np

arr1 = np.array([3, 4])
arr2 = np.array([1, 0])
avg = (arr1 + arr2) / 2
print("Average =", avg)

Average = [2. 2.]


In [ ]:
import numpy as np
arr1 = np.array([[3, 4],
                 [5, 6]])
arr2 = np.array([[1, 0],
                 [2, 3]])
# Average of two arrays

avg = (arr1 + arr2) / 2

print("Average of NumPy arrays:\n", avg)


# Mean

mean1 = np.mean(arr1)
mean2 = np.mean(arr2)

print("\nMean of arr1:", mean1)
print("Mean of arr2:", mean2)

# Median

median1 = np.median(arr1)
median2 = np.median(arr2)

print("\nMedian of arr1:", median1)
print("Median of arr2:", median2)

# Mode using NumPy only

# Flatten arrays into 1D
flat1 = arr1.flatten()
flat2 = arr2.flatten()

# Find unique values and counts
values1, counts1 = np.unique(flat1, return_counts=True)
values2, counts2 = np.unique(flat2, return_counts=True)

# Find mode
mode1 = values1[np.argmax(counts1)]
mode2 = values2[np.argmax(counts2)]

print("\nMode of arr1:", mode1)
print("Mode of arr2:", mode2)