In [7]:
import numpy as np

arr = np.array([1,2,3,4,5,6])
arr2d = arr.reshape(2,3)

print(arr2d)
print("Shape =", arr2d.shape)
print("Dimension =", arr2d.ndim)
print("Data Type =", arr2d.dtype)
print("Item Size =", arr2d.itemsize)

[[1 2 3]
 [4 5 6]]
Shape = (2, 3)
Dimension = 2
Data Type = int64
Item Size = 8


In [8]:
import numpy as np

arr = np.full((3,3), 9)
print(arr)

[[9 9 9]
 [9 9 9]
 [9 9 9]]


In [9]:
arr = np.arange(26, 46, 2)
print(arr)

[26 28 30 32 34 36 38 40 42 44]


In [10]:
import numpy as np

lst = [10,20,30,40,50]
arr = np.array(lst)
print(arr)

[10 20 30 40 50]


In [11]:
import numpy as np

arr = np.array([1,2,3,4,5])
print(arr[::-1])

[5 4 3 2 1]


In [12]:
import numpy as np

arr = np.arange(48).reshape(4,4,3)

print(arr[1])

[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


In [13]:
import numpy as np

arr = np.arange(1,17).reshape(4,4)

print(arr[1::2, ::2])

[[ 5  7]
 [13 15]]


In [14]:
import numpy as np

arr = np.arange(48).reshape(4,4,3)

print(arr[1, :2, :2])

[[12 13]
 [15 16]]


In [15]:
import numpy as np

arr = np.array([[23,56,78,93],
                [71,82,13,24]])

for i in range(arr.shape[0]):
    for j in range(arr.shape[1]):
        if arr[i,j] % 2 != 0:
            arr[i,j] = -1

print(arr)

[[-1 56 78 -1]
 [-1 82 -1 24]]


In [16]:
import numpy as np
arr = np.array([1,0,2,0,3,0,4])
print(np.nonzero(arr))

(array([0, 2, 4, 6]),)


In [17]:
import numpy as np
a = np.array([10,20,30])
b = np.array([1,2,3])
print("Addition =", a+b)
print("Subtraction =", a-b)
print("Multiplication =", a*b)
print("Division =", a/b)

Addition = [11 22 33]
Subtraction = [ 9 18 27]
Multiplication = [10 40 90]
Division = [10. 10. 10.]


In [18]:
import numpy as np
a = np.array([2,4,6])
b = np.array([1,3,5])
print(a*b)

[ 2 12 30]


In [19]:
import numpy as np

arr1 = np.array([15,20,25])
arr2 = np.array([10,40,37])

result = np.dot(arr1, arr2)

print(result)

1875
