In [1]:
import numpy as np

arr = np.array([[6, -8, 73, -110], [np.nan, -8, 0, 94]])

arr = np.nan_to_num(arr)

arr = arr[[1, 0], :][:, [1, 0, 2, 3]]
print(arr)

[[  -8.    0.    0.   94.]
 [  -8.    6.   73. -110.]]


In [4]:
import numpy as np

arr = np.random.rand(2, 3, 4)

new_arr = np.moveaxis(arr, 0, 2)
print(new_arr)

[[[0.40214727 0.15745033]
  [0.99748305 0.91609619]
  [0.2880817  0.63973167]
  [0.14036606 0.24481221]]

 [[0.32670013 0.94461187]
  [0.21258943 0.93796981]
  [0.47827083 0.87747319]
  [0.90475105 0.86372727]]

 [[0.25084596 0.92277201]
  [0.20718987 0.72694925]
  [0.78215343 0.73571101]
  [0.19225997 0.19757855]]]


In [5]:
import numpy as np

arr = np.array([[1, np.nan, 3], [4, 5, np.nan], [np.nan, 7, 9]])
means = np.nanmean(arr, axis=0)
arr[np.isnan(arr)] = np.take(means, np.where(np.isnan(arr))[1])
print(arr)

[[1.  6.  3. ]
 [4.  5.  6. ]
 [2.5 7.  9. ]]


In [7]:
import numpy as np
import pandas as pd

arr = np.array([6, -8, 73, -110, 0, 94])
arr = pd.Series(arr).replace(to_replace=arr[arr < 0], value=0).to_numpy()

print(arr)

[ 6  0 73  0  0 94]
